name: indexed_iterable
description: A simple delegate representing `Iterable`, like `List` and `set`, with index.
version: 1.0.2
homepage: https://www.gihwan.com

environment:
  sdk: ">=2.7.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
